FROM golang:{{ .Go }}-buster as go
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOBIN=/bin
RUN go install github.com/go-delve/delve/cmd/dlv@v1.8.2
ADD https://github.com/spiffe/spire/releases/download/v{{ .Spire }}/spire-{{ .Spire }}-linux-x86_64-glibc.tar.gz .
RUN tar xzvf spire-{{ .Spire }}-linux-x86_64-glibc.tar.gz -C /bin --strip=2 spire-{{ .Spire }}/bin/spire-server spire-{{ .Spire }}/bin/spire-agent

FROM go as build
WORKDIR /build
COPY go.mod go.sum ./
COPY ./internal/pkg/imports imports
RUN go build ./imports

COPY . .
RUN go build -o /bin/{{ .Name }} .

FROM build as test
CMD go test -test.v ./...

FROM test as debug
CMD dlv -l :40000 --headless=true --api-version=2 test -test.v ./...

FROM alpine as runtime
COPY --from=build /bin/{{ .Name }} /bin/{{ .Name }}
CMD /bin/{{ .Name }}
